### ISSUE TITLE
EXTRA_BINARGS are forced

### ISSUE THREAD

**Issue by appellation** [Bisa/factorio-init#53] opened 2016-04-26 17:20 UTC
Attempting to start a Factorio server on Ubuntu 14.04.3 without `EXTRA_BINARGS` doesn't seem to work.  I tried both using an empty string and removing it from `INVOCATION`, neither of which worked.
## Debug log when `EXTRA_BINARGS` is an empty string

```
factorio@xxxxxxxxxx:/home/ubuntu$ service factorio restart
DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
No running server, starting it...
DEBUG LOG: last modified save: /opt/factorio/saves/factorio-init-save.zip
DEBUG LOG: using existing factorio-init-save.zip
DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
```
## Debug log when removed from `INVOCATION`

```
factorio@xxxxxxxxxx:/home/ubuntu$ service factorio restart
DEBUG LOG: found pid: 1635
1983
28344
28797
28924
/etc/init.d/factorio: line 123: [: too many arguments
/etc/init.d/factorio: line 125: [: too many arguments
No running server, starting it...
DEBUG LOG: last modified save: /opt/factorio/saves/factorio-init-save.zip
DEBUG LOG: using existing factorio-init-save.zip
DEBUG LOG: found pid: 1635
1983
28344
28797
28924
29068
```

This output continued for a while before it quit.

**Comment by Bisa** [comment] 2016-05-01 12:55
Thank you, I'll see what I can do to remove the restriction

**Comment by Bisa** [comment] 2016-05-01 13:59
@appellation I'm unable to reproduce this with a fresh install of the latest pull from master (I removed the EXTRA_BINARGS from my INVOCATION)
- however, looking at your output it seems your find_pid() returns multiple pids, I'm guessing you have multiple server instances running on the same binary or something?

**Comment by Bisa** [comment] 2016-05-01 16:30
I've figured out the WHY, now I just need to find a solution.

The find_pid is incorrectly looking for a whitespace at the end of the output from ps, I might make a pragmatic fix or I might find a neat way to solve it, stay tuned :8ball:

**Comment by Bisa** [comment] 2016-05-01 16:41
hm, I got the auto-closing messed up but this is fixed in above mentioned commit so try to pull the latest master and try again =)

**Closed as completed by Bisa** 2016-05-01 16:41 UTC
Labels: bug

**Comment by appellation** [comment] 2016-05-02 21:33
It seems to have been fixed.  Thanks for the fix!
